#ifndef ULSBUSTYPES_H
#define ULSBUSTYPES_H
#include <inttypes.h>
#include <string.h>

#include "ULSBusConfig.h"
#include "udebug.h"

#define _ULS_OPERATION_KEY 0x24041982
#define __DEVICE_KEY                                           \
  (__DEVICE_UNIC_ID0 ^ __DEVICE_UNIC_ID1 ^ __DEVICE_UNIC_ID2 ^ \
   __DEVICE_UNIC_ID3)

/*
 * Device schema: the compressed object book a device carries (generated by
 * Scripts/uls_schema.py), read over GETOBJ as objects
 * ULS_SCHEMA_PAGE_ID_FIRST + n. Page 0 is the header alone, page n >= 1 the
 * n-th slice of the compressed stream. No book object may use these ids.
 */
#define ULS_SCHEMA_FORMAT (1)
#define ULS_SCHEMA_HEADER_SIZE (32)
#define ULS_SCHEMA_PAGE_ID_FIRST (0xFE00)
#define ULS_SCHEMA_PAGE_ID_LAST (0xFEFF)

typedef enum {
  ULSBUS_OBJECT_PERMISSION_READONLY = 0,
  ULSBUS_OBJECT_PERMISSION_WRITEONLY = 1,
  ULSBUS_OBJECT_PERMISSION_READWRITE = 2,
  ULSBUS_OBJECT_PERMISSION_PROTECTED = 3,
  ULSBUS_OBJECT_PERMISSION_CONFIG = 4,
  ULSBUS_OBJECT_PERMISSION_SYSCONFIG = 5,
  ULSBUS_OBJECT_PERMISSION_ADMIN = 6
} _ulsbus_obj_permissions;

class ULSListItem {
 public:
  ULSListItem() { pxnext = nullptr; };
  void *pxnext;
};

template <class T>
class ULSList {
 public:
  ULSList() : _head(nullptr) {};
  void begin() { _first = true; }
  bool next() {
    if (_first) {
      current = _head;
      _first = false;
    } else {
      if (current == nullptr) return false;
      current = (T *)current->pxnext;
    }
    if (current == nullptr) return false;
    return true;
  }
  void add(T *item) {
    if (_head == nullptr) {
      _head = item;  // add first item;
      //_head->pxnext = nullptr;
    } else {
      T *px = (T *)_head;
      while (px->pxnext != nullptr) {
        px = (T *)(px->pxnext);
      }
      px->pxnext = item;  // add item;
      // item->pxnext = nullptr;
    }
  };
  void remove(T *item) {
    // Todo Add remove code
    (void)item;
  };
  T *current;

 private:
  bool _first;
  T *_head;
};

#endif  // ULSBUSTYPES_H
