#ifndef ULSDEVICES_H
#define ULSDEVICES_H

//#define __ULS_DEVICE_TYPE_PCR1 (0x0001)
#define __ULS_DEVICE_TYPE_ULSQT1R1 (0x0010)
#define __ULS_DEVICE_TYPE_ULSQR1R1 (0x0011)
#define __ULS_DEVICE_TYPE_ULSQG1R1 (0x0012)
#define __ULS_DEVICE_TYPE_ULSQM1R1 (0x0013)

//#define __ULS_DEVICE_TYPE_PCR1_NAME "PCR1"
#define __ULS_DEVICE_TYPE_ULSQT1R1_NAME "ULSQT1R1"
#define __ULS_DEVICE_TYPE_ULSQR1R1_NAME "ULSQR1R1"
#define __ULS_DEVICE_TYPE_ULSQG1R1_NAME "ULSQG1R1"
#define __ULS_DEVICE_TYPE_ULSQM1R1_NAME "ULSQM1R1"



#endif // ULSDEVICES_H
